package mod.upcraftlp.cobwebs.proxy;

import java.util.Arrays;

import mod.upcraftlp.cobwebs.Reference;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

public class ClientProxy extends CommonProxy {
	
	@Override
	public void preInit(FMLPreInitializationEvent event) {
		super.preInit(event);
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.authorList = Arrays.asList(Reference.AUTHORS);
		data.modId = Reference.MOD_ID;
		data.name = Reference.MODNAME;
		data.description = "Make them cobwebs burn!";
		data.credits = Reference.AUTHORS[0];
		data.url = Reference.URL;
	}
	
}
